#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan  9 10:48:00 2024

@author: sp3660


tkinter copy of yuris app
"""


import datetime
import tkinter as tk
from tkinter import ttk


class Gui(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title('Caiman Sorter')
        self.geometry('1200x1200')
        self.todays_date=datetime.date.today().strftime("%Y%m%d")
        
        self.structure={'main':{'object':'',
                                'data_loading':{'object':'',
                                                'labels':{'Load Data':{},
                                                          'Log':{},
                                                          },
                                                'buttons':{'Browse':{},
                                                           'Load':{},
                                                           'Save data':{},
                                                           'Save osp':{}
                                                           },
                                                'text':{'Loading Data':{},
                                                          'Loging':{},
                                                          }
                                                
                                                },
                                
                                'visual_parmeter':{'object':'',
                                                   'panels':{'Bakground Plot':{ 'buttons':{'Components':{},
                                                                                           'Weighted comp':{},
                                                                                           'Weighted comp + bkg':{}
                                                                                           },
                                                                               'labels':{'Background plot':{},
                                                                                         }
                                                                               },
                                                             'Plot Contours':{ 'buttons':{'None':{},
                                                                                          'SNR Caiman':{},
                                                                                          'SNR2':{},
                                                                                          'CNN':{},
                                                                                          'R values':{},
                                                                                          'Firing stability':{}
            
                                                                                          },
                                                                              'labels':{'Plot Contours':{},
                                                                                        }
                                                                              },
                                                             },
                                                   'labels':{'Manual edits':{},
                                                             'Log':{},
                                                             'Contour limits':{},
                                                             'Min':{},
                                                             'Max':{},
                                                             'Visualization params':{}
                                                             },
                                                   'buttons':{'Toggle anual edits':{},
                                                              'Reset manual edits':{},
                                                              },
                                                   'entry':{'Min':{},
                                                             'Max':{},
                                                             },
                                                   'plots':{'contour color':{}
                                                            },
                                                   
                                                   },
                              
                                'tabed_processing':{'object':'',
                                                    'Tabs':{'Spatial components':{'object':'',
                                                                                  'plots':{'Accepted':{},
                                                                                           'Rejected':{}
                                                                                            }
                                                                                  },
                                                            'Deconvolution':{'object':'',
                                                                             'tabbed_options':{'object':'',
                                                                                               'Tabs':{'smooth df/dt':{'object':'',
                                                                                                                       'labels':{'Signal extraciotn params':{},
                                                                                                                                 'First Derivative':{},
                                                                                                                                 'Gaussian sigma (ms)':{},
                                                                                                                                 'Plotting params':{},
                                                                                                                                 'Threshold mag (z)':{},
                                                                                                                                 'Scale':{},
                                                                                                                                 'Shift':{},
                                                                                                                                 },
                                                                                                                       'button':{'Plot kernel':{},
            
                                                                                                                                 },
                                                                                                                       'entries':{'Gaussian sigma (ms)':{},
                                                                                                                                 'Threshold mag (z)':{},
                                                                                                                                 'Scale':{},
                                                                                                                                 'Shift':{},
                                                                                                                                 },
                                                             
                                                                                                                       'checkboxes':{'Convolve with gaussian kernel':{},
                                                                                                                                     'Rectify':{},
                                                                                                                                     'Normalize':{},
                                                                                                                                     'Apply threshold':{},
                                                                                                                                     'Plot threshold':{},
                                                                                                                                     },       
                                                                                                                       },
                                                                                                       'constrained foopsi':{'object':'',
                                                                                                                             'labels':{'Deconvolution params':{},
                                                                                                                                         'AR model':{},
                                                                                                                                         'Tau rise (sec)':{},
                                                                                                                                         'Tau decay (sec)':{},
                                                                                                                                         'Gaussian sigma (ms)':{},
                                                                                                                                         'Post deconvolution params':{},
                                                                                                                                         'Plotting params':{},
                                                                                                                                         'Scale':{},
                                                                                                                                         'Shift':{},
                                                                                                                                         },
                                                                                                                             'button':{'AR model switch':{},
                                                                                                                                       'Plot kernel':{},
            
                                                                                                                                         },
                                                                                                                             'entries':{ 'Tau rise (sec)':{},
                                                                                                                                        'Tau decay (sec)':{},
                                                                                                                                        'Gaussian sigma (ms)':{},
                                                                                                                                        'Scale':{},
                                                                                                                                        'Shift':{},
                                                                                                                                         },                                                        
                                                                                                                             'checkboxes':{'Use manual time constants':{},
                                                                                                                                           'Convolve with gaussian kernel':{},                                                                                                  
                                                                                                                                           },
                                                                                                                             },
                                                                                                       'MCMC':{'object':'',
                                                                                                               'labels':{'Deconvolution params':{},
                                                                                                                           'AR model':{},
                                                                                                                           'Tau rise (sec)':{},
                                                                                                                           'Tau decay (sec)':{},
                                                                                                                           'Gaussian sigma (ms)':{},
                                                                                                                           'Post deconvolution params':{},
                                                                                                                           'Plotting params':{},
                                                                                                                           'Scale':{},
                                                                                                                           'Shift':{},
                                                                                                                           'B - Number of burn in samples (default 200)':{},
                                                                                                                           'N - Number of samples after burn in  (default 500)':{}
                                                                                                                           },
                                                                                                               'button':{'AR model switch':{},
                                                                                                                         'Plot kernel':{},
                                                                                                                         'Plot MCMC SAMPLES details':{}
                                                                                                                           },
                                                                                                               'entries':{ 'Tau rise (sec)':{},
                                                                                                                          'Tau decay (sec)':{},
                                                                                                                          'Gaussian sigma (ms)':{},
                                                                                                                          'Scale':{},
                                                                                                                          'Shift':{},
                                                                                                                          'B - Number of burn in samples (default 200)':{},
                                                                                                                          'N - Number of samples after burn in  (default 500)':{}
                                                                                                                           },                                         
                                                                                                               'checkboxes':{'Use manual time constants':{},
                                                                                                                             'Convolve with gaussian kernel':{},
                                                                                                                             'Save SAMPLES MCMC outputs':{}                                                                                   
                                                                                                                             },
                                                                                                               },
                                                                                                       },
                                                                                               },
                                                                             'labels':{'Cell':{},
                                                                                       'Estimated time constant ar1':{},
                                                                                       'Tau decay sec':{},
                                                                                       'Estimated time constant ar2':{},
                                                                                       'Tau rise (sec)':{},
                                                                                       'Tau decay (sec)':{},
                                                                                       'Data frame rate (fps)':{},
                                                                                       'Plot smooth dfof':{},
                                                                                       'Plot const foopsi':{},
                                                                                       'Plot MCMC':{},
                                                                                 },
                                                                             'button':{'Run current cell':{},
                                                                                       'Run accpeted cells':{},
                                                                                       'Run all cell':{},
                                                                                       'Plot smooth dfof switch':{},
                                                                                       'Plot const foopsi switch':{},
                                                                                       'Plot MCMC switch':{},
                                                                                       'Update plots':{},
                                                                                       
                                                                                       
                                                                                       },
                                                                             'entries':{'Cell':{},
                                                                                       'Tau decay sec':{},
                                                                                       'Tau rise (sec)':{},
                                                                                       'Tau decay (sec)':{},
                                                                                       'Data frame rate (fps)':{},
                                                                                       },
                                                                             'checkboxes':{'Overwrite':{}
                                                                                           }, 
                                                                             }
                                                            }
                                        },
                                'trace_plotting':{'object':'',
                                                  'plots':{'Traces':{}
                                                           },
                                        },
                                'plotting_options':{'object':'',                                        
                                                   'labels':{'Ca trace':{},
                                                             'Plot C':{},
                                                             'Plot Raw':{},
                                                             'Window':{},
                                                             'Plot Spikes':{},
                                                             'Plot Last C':{},
                                              
                                                       },
                                                   'button':{'Plot C switch':{},
                                                             'Plot Raw switch':{},
                                                             'Plot Spikes switch':{},
                                                             'Plot Last C switch':{},
                                                             'Smooth raw':{},
                                                             'Arrow up':{},
                                                             'Arrow down':{},
                                                             },
                                                   'entries':{'Window':{},              
                                                             },
                                               },
                                'parameter_explorer':{'object':'',
                                                      'Tabs':{'object':'',
                                                              'Current Component':{'object':'',
                                                                                   'labels':{'SNR Caiman':{},
                                                                                             'SNR2':{},
                                                                                             'CNN prob':{},
                                                                                             'r_val':{},
                                                                                             'Firing stability':{},
                                                                                             'Peaks ave':{},
                                                                                             'Std noise':{}
                                                                                             },
                                                                                   'entry':{'SNR Caiman':{},
                                                                                            'SNR2':{},
                                                                                            'CNN prob':{},
                                                                                            'r_val':{},
                                                                                            'Firing stability':{},
                                                                                            'Peaks ave':{},
                                                                                            'Std noise':{}
                                                                                            },
                                                                                   'plots':{'Cell':{}
                                                                                            },
                                                                                   
                                                                  },
                                                              'Evaluate Params':{'object':'',
                                                                                 'panels':{'Caiman evaluate':{ 'panels':{'SNR':{'labels':{'SNR':{},
                                                                                                                                         'SNR thres':{},
                                                                                                                                         'Lowest thres':{},
                                                                                                                                         },
                                                                                                                               'entry':{'SNR thres':{},
                                                                                                                                        'Lowest thres':{},
                                                                                                                                        },
                                                                                                                               'buttons':{'Arrow up left':{},
                                                                                                                                          'Arrow down left':{},
                                                                                                                                          'Arrow up right':{},
                                                                                                                                          'Arrow down right':{},
                                                                                                                                          },
                                                                                                                               },
                                                                                                                         'CNN prob [0, 1]':{'labels':{'CNN prob [0, 1]':{},
                                                                                                                                                     'CNN prob  thres':{},
                                                                                                                                                     'Lowest thres':{},
                                                                                                                                                     },
                                                                                                                                           'entry':{'SCNN prob  thres':{},
                                                                                                                                                    'Lowest thres':{},
                                                                                                                                                    },
                                                                                                                                           'buttons':{'Arrow up left':{},
                                                                                                                                                      'Arrow down left':{},
                                                                                                                                                      'Arrow up right':{},
                                                                                                                                                      'Arrow down right':{},
                                                                                                                                                      },
                                                                                                                                           },
                                                                                                                         'R values [0, 1]':{'labels':{'R values [0, 1]':{},
                                                                                                                                                     'R val thres':{},
                                                                                                                                                     'Lowest thres':{},
                                                                                                                                                     },
                                                                                                                                           'entry':{'R val thres':{},
                                                                                                                                                    'Lowest thres':{},
                                                                                                                                                    },
                                                                                                                                           'buttons':{'Arrow up left':{},
                                                                                                                                                      'Arrow down left':{},
                                                                                                                                                      'Arrow up right':{},
                                                                                                                                                      'Arrow down right':{},
                                                                                                                                                      },
                                                                                                                                           }
                                                                                                                         },
                                                                                                             'labels':{'Caiman evaluate':{},
                                                                                                                       },
                                                                                                             'canvas':{}
                                                                                                             },
                                                                                           'Reject threshold':{'checkboxes':{'SNR Caiman':{},
                                                                                                                             'SNR2':{},
                                                                                                                             'CNN prob':{},
                                                                                                                             'R values':{},
                                                                                                                             'Min signal frac':{},
                                                                                                                             'Firing stability':{}
                                                                                                                             },
                                                                                                                'entries':{'SNR Caiman':{},
                                                                                                                           'SNR2':{},
                                                                                                                           'CNN prob':{},
                                                                                                                           'R values':{},
                                                                                                                           'Min signal frac':{},
                                                                                                                           'Firing stability':{}
                                                                                                                          },
                                                                                                                'canvas':{}
                                                                                                                },
                                                                                           },
                                                                                 'labels':{'Caiman evaluate':{},
                                                                                           'Reject Threshold':{},                                                        
                                                                                           },
                                                                                 'buttons':{'Evaluate components':{},
                                                                                            },
                                                                  },
                                                              'Params Distributions':{'object':'',                                                                         
                                                                                      'buttons':{'Plot SNR Caiman':{},
                                                                                               'Plot NR2':{},
                                                                                               'Plot CNN':{},
                                                                                               'Plot Rval':{},
                                                                                               },
                                                                                      'plots':{'Density':{}
                                                                                               },
                                                                  },
                                                              'Params':{'object':'',
                                                                        'labels':{'OnACID parameters':{},
                                                                                  'Processing parameters':{},
                                                                                  'Dims':{},
                                                                                  'Decay time':{},
                                                                                  'Frame Rate':{},
                                                                                  'gSig':{},
                                                                                  'Epochs':{},
                                                                                  'p (AR model)':{},
                                                                                  'ds_factor':{},
                                                                                  'peaks to ave':{},
                                                                                  'peak bin size':{},
                                                                                  },
                                                                  },
                                                              }
                                        },
                                'cell_selector':{'object':'',
                                                 'labels':{'Cell selection':{},
                                                           'Cell number':{},
                                                           'Cell catergory':{},                                          
                                                           },
                                                 'buttons':{'Press up/down key to change cell num':{},
                                                           'Accepted':{},
                                                           'Rejected':{},   
                                                           'All':{},   
                                                           'Arrow up':{},   
                                                           'Arrow down':{},  
                                                           },
                                                 'entries':{'Cell number':{},
                                                           }
                                        }
                     },
            }